package:
  name: altair
  version: 5.3.0
  top-level:
    - altair
source:
  url: https://files.pythonhosted.org/packages/bd/3c/a0934e25e5eed622b35594261edff75bfa342882d651daa33961fdb4fbf0/altair-5.3.0.tar.gz
  sha256: 5a268b1a0983b23d8f9129f819f956174aa7aea2719ed55a52eba9979b9f6675
requirements:
  run:
    - Jinja2
    - jsonschema
    - numpy
    - packaging
    - pandas
    - toolz
    - typing-extensions
about:
  home: http://altair-viz.github.io
  PyPI: https://pypi.org/project/altair
  summary: "Altair: A declarative statistical visualization library for Python."
  license: BSD 3-clause
