package:
  name: altair
  version: 5.0.0
  top-level:
    - altair
source:
  url: https://files.pythonhosted.org/packages/2e/b8/49d377d9a7a85dc24e35d70384fc5ae7b19db6f8ee9d23d36337675c602e/altair-5.0.0-py3-none-any.whl
  sha256: e7deed321f61a3ec752186ae96e97b44a1353de142928c1934fb211e9f0bfe9e
requirements:
  run:
    - Jinja2
    - jsonschema
    - numpy
    - pandas
    - toolz
    - entrypoints
    - typing-extensions
about:
  home: http://altair-viz.github.io
  PyPI: https://pypi.org/project/altair
  summary: "Altair: A declarative statistical visualization library for Python."
  license: BSD 3-clause
