# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Draco
author: CMU Data Interaction Group
logo: logo-light.png

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/cmudig/draco2 # Online location of your book
  path_to_book: docs # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

launch_buttons:
  notebook_interface: jupyterlab

parse:
  myst_extended_syntax: true
