# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Draco
author: CMU Data Interaction Group
copyright: "2023"
logo: logo-light.png

execute:
  timeout: 600

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/cmudig/draco2 # Online location of your book
  path_to_book: docs # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: "favicon.ico"
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: https://mybinder.org

parse:
  myst_enable_extensions:
    - linkify
    - substitution
    - dollarmath

sphinx:
  extra_extensions:
    - "sphinx.ext.autodoc"
    - "sphinx_autodoc_typehints"
  config:
    # Possible `autodoc` configs: https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#configuration
    autodoc_preserve_defaults: True
    # Print tracebacks for execution errors directly into the terminal, useful in CI (https://jupyterbook.org/en/stable/content/execute.html#execution-tracebacks-in-the-terminal)
    nb_execution_show_tb: True
    nb_execution_timeout: 600

bibtex_bibfiles:
  - references.bib
