name: Build and publish docs

on:
  push:
    branches:
      - main
      - ci/test*

jobs:
  docs:
    name: Build Jupyter Book and publish to GitHub Pages
    runs-on: ubuntu-latest

    # This job is responsible for the GH Pages deployment
    environment:
      name: github-pages
      url: ${{ steps.gh_pages_deployment.outputs.page_url }}

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      # Required to execute notebooks with Python modules wrapping Node.js modules, such as Draco 1
      - name: Setup Node
        uses: actions/setup-node@v4

      # Installing system dependencies required by notebooks to be executed
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y gringo

      - name: Make book
        run: make book

      - name: Display HTML bundle tree
        run: find docs/_build/html/ | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Documentation Site Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_build/html

      - name: Deploy to GitHub Pages
        id: gh_pages_deployment
        uses: actions/deploy-pages@v4
