name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8

      - shell: bash -l {0}
        run: |
          which pip
          pip --version
          which python
          python --version
          which conda
          conda --version


      - shell: bash -l {0}
        run: |
          pip install mypy
          pip install wheel

      - name: Install
        shell: bash -l {0}
        run: |
          pip install poetry==1.0.5
          poetry install
          conda install -c potassco clingo
          pip install -e .


      - name: Tests
        shell: bash -l {0}
        run: python setup.py test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
